apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-ingress
  namespace: springboot-app
spec:
  rules:
  - host: springboot.local       # map this host in /etc/hosts to minikube IP
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: springboot-crud-svc
            port:
              number: 8080
